language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - rp.loaiza@alumnos.upm.es

script:
#Test unitario y de integracion en develop
- mvn verify --settings settings.xml
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=rploaiza-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$passwordSonar --settings settings.xml
